-- Production seed intentionally left empty.
-- ClinicFlow AI does not insert fake clinics, patients, conversations, or billing records.
-- Real tenant data is created through Supabase Auth, onboarding, provider webhooks, and audited server actions.
