export const protectedRoutes = [
  "/dashboard",
  "/onboarding",
  "/operations",
  "/alerts",
  "/activity",
  "/ai",
  "/reception",
  "/knowledge",
  "/escalations",
  "/integrations",
  "/connections",
  "/sync",
  "/performance",
  "/scorecards",
  "/benchmarks",
  "/forecasting",
  "/pipeline",
  "/tasks",
  "/reactivation",
  "/opportunities",
  "/lifecycle",
  "/executive",
  "/insights",
  "/briefings",
  "/risks",
  "/performance-center",
  "/enterprise",
  "/organisation",
  "/locations",
  "/governance",
  "/compliance",
  "/audit",
  "/regional",
  "/sla",
  "/platform",
  "/saas",
  "/factory",
  "/admin",
  "/system",
  "/branding",
  "/developer",
  "/feature-flags",
  "/rules",
  "/execution",
  "/automation-runs",
  "/triggers",
  "/actions",
  "/patients",
  "/calls",
  "/calendar",
  "/inbox",
  "/campaigns",
  "/communications",
  "/engagement",
  "/threads",
  "/reminders",
  "/conversations",
  "/recovery",
  "/analytics",
  "/analytics-engine",
  "/executive-reports",
  "/trends",
  "/health-scores",
  "/kpis",
  "/billing",
  "/subscriptions",
  "/plans",
  "/usage",
  "/entitlements",
  "/workflows",
  "/automations",
  "/notifications",
  "/settings",
  "/team",
  "/account",
  "/security",
];

export const dashboardNavItems = [
  { href: "/dashboard", label: "Overview" },
  { href: "/operations", label: "Operations" },
  { href: "/alerts", label: "Alerts" },
  { href: "/ai", label: "AI" },
  { href: "/reception", label: "Reception" },
  { href: "/integrations", label: "Integrations" },
  { href: "/connections", label: "Connections" },
  { href: "/pipeline", label: "Pipeline" },
  { href: "/executive", label: "Executive" },
  { href: "/enterprise", label: "Enterprise" },
  { href: "/platform", label: "Platform" },
  { href: "/saas", label: "SaaS" },
  { href: "/factory", label: "Factory" },
  { href: "/billing", label: "Billing" },
  { href: "/performance", label: "Performance" },
  { href: "/analytics", label: "Analytics" },
  { href: "/analytics-engine", label: "Analytics Engine" },
  { href: "/calls", label: "Calls" },
  { href: "/calendar", label: "Calendar" },
  { href: "/recovery", label: "Recovery" },
  { href: "/patients", label: "Patients" },
  { href: "/communications", label: "Comms" },
  { href: "/inbox", label: "Inbox" },
  { href: "/campaigns", label: "Campaigns" },
  { href: "/workflows", label: "Workflows" },
  { href: "/rules", label: "Rules" },
  { href: "/automations", label: "Automations" },
  { href: "/team", label: "Team" },
  { href: "/settings", label: "Settings" },
];
